export const colors = {
  primary: '#2563EB',
  primaryLight: '#EFF6FF',
  primaryBorder: '#BFDBFE',
  accent: '#0EA5E9',
  danger: '#EF4444',
  dangerLight: '#FEF2F2',
  dangerBorder: '#FECACA',
  success: '#10B981',
  successLight: '#ECFDF5',
  warning: '#F59E0B',
  warningLight: '#FFFBEB',
  warningBorder: '#FDE68A',
  text: '#1D2129',
  textSecondary: '#4E5969',
  textMuted: '#86909C',
  textFaint: '#C9CDD4',
  bg: '#F5F6FA',
  bgCard: '#FFFFFF',
  bgSurface: '#F7F8FA',
  border: '#E5E6EB',
  borderLight: '#F5F6F7',
} as const
